project_name: status-client
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - 386
      - amd64
      - mips
      - mipsle
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
archives:
  - name_template: "status-client_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
